[package]
name = "carina_core_protocol"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]

[dependencies]
clippy = { version = "0.0.195", optional = true }
failure = "0.1.1"
log = "0.4.1"
sodiumoxide = "0.0.16"

[features]
default = []
dev = ["clippy"]