sudo: false

language: rust

notifications:
  email: false

cache: 
  directories:
    - $HOME/libsodium
    - $HOME/.cargo

rust:
  - stable
  - beta
  - nightly

install:
  - ./scripts/travis-install-libsodium.sh
  - export PKG_CONFIG_PATH=$HOME/libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH