[profile.release]
lto = true
panic = 'abort'

[workspace]
members = [
  "async",
  "connection_manager",
  "debug",
  "hooks",
  "file",
  "hole_puncher",
  "logging",
  "network",
  "peer",
  "protocol"
]