version: '3'
services:
  peer_1:
    build:
      context: .
      dockerfile: dockerfile
    links:
      - postgres
    environment:
      - CONFIG_FILE=./config.peer1.yml
    networks:
      - network_1
    ports:
      - '8001:8001'

  postgres:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - network_1

networks:
  network_1:
    driver: bridge