[package]
authors = ["lholznagel <lars.holznagel@outlook.com>"]
name = "blockchain_connection_manager"
version = "0.1.0"

[dependencies]
blockchain_logging = { path = "../logging" }
blockchain_network = { path = "../network" }
blockchain_protocol = { path = "../protocol" }