%YAML 1.2
---
port: 8003

database:
  address: "localhost"
  port: 5432
  user: "peer3"
  password: "peer3"

info: 
  address: "localhost"
  name: "Peer 3"

peers:
  - address: "localhost"
    port: 8001
  - address: "localhost"
    port: 8002