%YAML 1.2
---
port: 8003

database:
  address: "db"
  port: 5432
  user: "peer3"
  password: "peer3"

info: 
  address: "peer_3"
  name: "Peer 3"

peers:
  - address: "peer_1"
    port: 8001
  - address: "peer_2"
    port: 8002