%YAML 1.2
---
port: 8001

database:
  address: "localhost"
  port: 5432
  user: "peer1"
  password: "peer1"

info: 
  name: "Peer 1"

peers:
  - address: "localhost"
    port: 8002
    name: "Peer 2"
  - address: "localhost"
    port: 8003
    name: "Peer 3"