%YAML 1.2
---
port: 8001

database:
  address: "localhost"
  port: 5432
  user: "peer1"
  password: "peer1"

info: 
  address: "localhost"
  name: "Peer 1"

peers:
  - address: "localhost"
    port: 8002
  - address: "localhost"
    port: 8003