[package]
authors = ["lholznagel <lars.holznagel@outlook.com>"]
name = "blockchain_cli"
version = "0.1.0"

[dependencies]
clap = "2.26.0"
openssl = "0.9.17"
serde = "1.0.11"
serde_derive = "1.0.11"
toml = "0.4.5"
