[package]
authors = ["lholznagel <contact@lholznagel.info>"]
name = "blockchain_network"
version = "0.1.0"

[dependencies]
blockchain_hooks = { path = "../hooks" }
blockchain_protocol = { path = "../protocol" }
