FROM    phusion/baseimage:latest

COPY    ./carina_peer /etc/service/carina_peer/peer
COPY    ./run.sh /etc/service/carina_peer/run

RUN     chmod +x /etc/service/carina_peer/run && \
        chmod +x /etc/service/carina_peer/peer && \
        chown -R root: /etc/service/carina_peer