FROM    phusion/baseimage:latest

COPY    ./blockchain_peer /etc/service/blockchain_peer/peer
COPY    ./run.sh /etc/service/blockchain_peer/run

RUN     chmod +x /etc/service/blockchain_peer/run && \
        chmod +x /etc/service/blockchain_peer/peer && \
        chown -R root: /etc/service/blockchain_peer