[package]
name = "carina_core"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]

[dependencies]
base64 = "0.9.1"
clippy = { version = "0.0.195", optional = true }
failure = "0.1.1"
log = "0.4.1"
yaml-rust = "0.4.0"
sodiumoxide = "0.0.16"

[features]
default = []
dev = ["clippy"]