%YAML 1.2
---
port: 8002

database:
  address: "db"
  port: 5432
  user: "peer2"
  password: "peer2"

info: 
  address: "peer_2"
  name: "Peer 2"

peers:
  - address: "peer_1"
    port: 8001
  - address: "peer_3"
    port: 8003
