#!/bin/bash

USERS=('node_1')

for i in "${USERS[@]}"; do
    docker-compose exec postgres psql -c "CREATE USER $i PASSWORD '$i';" -U postgres

    docker-compose exec postgres psql -c "CREATE DATABASE $i;" -U postgres

    docker-compose exec postgres psql -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;" -U postgres $i

    docker-compose exec postgres psql -c "CREATE TABLE IF NOT EXISTS nodes (
      -- name of the node
      name              TEXT                      NOT NULL,
      -- id of the node, generated by the registering node
      node_id           UUID        PRIMARY KEY   NOT NULL,
      -- timestamp when the node as registered itself
      registered_at     BIGINT                    NOT NULL
    );" -U postgres $i

    docker-compose exec postgres psql -c "GRANT SELECT, UPDATE, INSERT, DELETE ON nodes TO $i;" -U postgres $i
done