[package]
name = "carina_peer_cli"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]

[dependencies]
carina_peer = { path = "../peer" }
carina_logging = { path = "../logging" }
clippy = { version = "0.0.190", optional = true }
clap = "2.31.2"
log = { version = "0.4.1", features = ["std"] }

[features]
default = []
dev = ["clippy"]